package codexharness

import (
	"encoding/json"
	"time"

	"github.com/futrx-com/remote.futrx.com/internal/agent"
)

// These are the account/rateLimits shapes generated by the pinned app-server
// protocol. Read responses may contain several metered products; only the
// Codex bucket describes the subscription displayed by Remote.
type appServerRateLimits struct {
	RateLimits          json.RawMessage            `json:"rateLimits"`
	RateLimitsByLimitID map[string]json.RawMessage `json:"rateLimitsByLimitId"`
}

type appServerRateLimitSnapshot struct {
	LimitID   string                    `json:"limitId"`
	Primary   *appServerRateLimitWindow `json:"primary"`
	Secondary *appServerRateLimitWindow `json:"secondary"`
}

type appServerRateLimitWindow struct {
	UsedPercent        *float64 `json:"usedPercent"`
	WindowDurationMins *int64   `json:"windowDurationMins"`
	ResetsAt           *int64   `json:"resetsAt"`
}

func codexQuotaReadings(raw json.RawMessage, now int64) []agent.Quota {
	var limits appServerRateLimits
	if json.Unmarshal(raw, &limits) != nil {
		return nil
	}
	bucket := limits.RateLimits
	if limits.RateLimitsByLimitID != nil {
		bucket = limits.RateLimitsByLimitID["codex"]
	}
	var snapshot appServerRateLimitSnapshot
	if json.Unmarshal(bucket, &snapshot) != nil || (snapshot.LimitID != "" && snapshot.LimitID != "codex") {
		return nil
	}
	// A legacy single-bucket snapshot may omit limitId. Explicitly identified
	// products and multi-bucket responses must never fall back to that default.
	windows := make(map[agent.QuotaWindow]agent.Quota, 2)
	for _, source := range []*appServerRateLimitWindow{snapshot.Primary, snapshot.Secondary} {
		if source == nil || source.UsedPercent == nil || *source.UsedPercent < 0 || source.WindowDurationMins == nil {
			continue
		}
		var window agent.QuotaWindow
		switch *source.WindowDurationMins {
		case 300:
			window = agent.QuotaWindowSession
		case 10080:
			window = agent.QuotaWindowWeekly
		default:
			continue
		}
		if _, exists := windows[window]; exists {
			continue
		}
		quota := agent.Quota{Window: window, UsedPercent: source.UsedPercent, MeasuredAt: now}
		if source.ResetsAt != nil && *source.ResetsAt > 0 {
			quota.ResetsAt = *source.ResetsAt
		}
		windows[window] = quota
	}
	var readings []agent.Quota
	for _, window := range []agent.QuotaWindow{agent.QuotaWindowSession, agent.QuotaWindowWeekly} {
		if quota, exists := windows[window]; exists {
			readings = append(readings, quota)
		}
	}
	return readings
}

func (parser *appServerEventParser) quotaEvents(now int64, method string, raw json.RawMessage, initial bool) []agent.Event {
	if parser.req.Provider != agent.ProviderCodex {
		return nil
	}
	var events []agent.Event
	for _, quota := range codexQuotaReadings(raw, now) {
		// The startup request and rolling notifications are independent. A late
		// initial response may fill missing windows, but cannot replace one that
		// has already received a live observation during this run.
		if initial && parser.liveQuotaWindows[quota.Window] {
			continue
		}
		if !initial {
			if parser.liveQuotaWindows == nil {
				parser.liveQuotaWindows = make(map[agent.QuotaWindow]bool, 2)
			}
			parser.liveQuotaWindows[quota.Window] = true
		}
		events = append(events, parser.event(now, method, agent.EventQuotaUpdated, raw, func(event *agent.Event) {
			event.Quota = &quota
		}))
	}
	return events
}

func (run *appServerRun) requestInitialQuota() {
	if run.req.Provider != agent.ProviderCodex {
		return
	}
	// This request does not gate thread/turn startup and is never awaited.
	// Unsupported or unauthenticated account reads must not fail a prompt.
	run.quotaReadPending = true
	if err := run.process.write(map[string]any{
		"method": "account/rateLimits/read",
		"id":     appServerRateLimitsRequestID,
	}); err != nil {
		run.quotaReadPending = false
	}
}

func (run *appServerRun) handleInitialQuota(envelope appServerEnvelope) {
	if !run.quotaReadPending {
		return
	}
	run.quotaReadPending = false
	if envelope.Error != nil || run.terminal {
		return
	}
	for _, event := range run.eventParser.quotaEvents(time.Now().UnixMilli(), "account/rateLimits/read", envelope.Result, true) {
		run.emit(event)
	}
}
